---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.2
  hooks:
    - id: pyupgrade

- repo: https://github.com/crate-ci/typos
  rev: v1.19.0
  hooks:
    - id: typos

# - repo: https://github.com/jazzband/pip-tools
#   rev: 6.12.0
#   hooks:
#     - id: pip-compile

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.4
  hooks:
    - id: ruff
    - id: ruff-format
