[tool.poetry]
name = "mlops-2024"
version = "0.1.0"
description = "ML Ops"
authors = ["Valiev Karim"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
